### ISSUE TITLE
AnalyzerFuntion IAM Role changed to Serverless Policies

### ISSUE THREAD

**Issue by komikoni** [komikoni/sam-binaryalert#6]
AWS::Serverless::Function is not work DependOn.

Redundant definition because it causes an error in SQS authorization
(AWSLambdaSQSQueueExecutionRole)

```
  LambdaFunctionAnalyzer: # lambda.tf module binaryalert_analyzer
    Type: AWS::Serverless::Function
    # DependOn: IAMPolicy # Not Work https://github.com/awslabs/serverless-application-model/issues/68
```

```
  IAMRole: # main.tf resource aws_iam_role role
    Type: AWS::IAM::Role
    Properties:
      Path: /
      # RoleName: !Sub ${NamePrefix}_binaryalert_analyzer_role # Only works with CAPABILITY_IAM
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowLambdaToAssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole # add
        - !Ref IAMManagedPolicy

```
